
- name: Load a variables
  include_vars: "../vars/env/{{ env }}.yml"

- name: Load a variables
  include_vars: "../vars/vault.yml"

- git:
    repo: "{{ git.repo }}"
    dest: /var/www
    version: "{{ git.branch }}"

