---

- hosts: "elk"
  remote_user: root
  become: no
  tasks:
    - name: Usage
      debug:
        msg: ""
    - name: Add java repo
      apt_repository:
        repo: 'ppa:webupd8team/java'
        codename: 'xenial'
        update_cache: yes
    - name: Install java
      apt:
        name: 'oracle-java8-installer'
    - name: add elastic repo key
      apt_key:
        url: "https://packages.elastic.co/GPG-KEY-elasticsearch"
        state: present
    - name: Add elasticsearch repo
      apt_repository:
        repo: 'deb http://packages.elastic.co/elasticsearch/2.x/debian stable main'
        state: present
        update_cache: yes
    - name: Install elasticsearc
      apt:
        name: 'elasticsearch'
    - name: Enable elasticsearch service
      service:
        name: elasticsearch
        state: started
        enabled: yes
    - name: Add kibana
      apt_repository:
        repo: 'deb http://packages.elastic.co/kibana/4.4/debian stable main'
        state: present
        update_cache: yes
    - name: Install kibana
      apt:
        name: 'kibana'
    - name: Enable kibana service
      service:
        name: kibana
        state: started
        enabled: yes
    - name: Add logstash
      apt_repository:
        repo: 'deb http://packages.elastic.co/logstash/2.2/debian stable main'
        state: present
        update_cache: yes
    - name: Install logstash
      apt:
        name: 'logstash'
    - name: Create logstash systemd service file
      copy:
        src: ../logstash/logstash.service
        dest: /lib/systemd/system/logstash.service
        mode: 0644
    - name: Enable logstash service
      service:
        name: logstash
        enabled: yes
        state: started
        daemon_reload: yes
