---
- hosts: "{{ hosts|default('*') }}"
  remote_user: root
  become: no
  tasks:

  - name: Install apache2
    apt:
      name: 'apache2'
      update_cache: yes

  - name: Ensure .ssh directory exists.
    file:
      dest: /root/.ssh
      mode: 0700
      owner: root
      state: directory

  - name: Install ssh key
    copy:
      content: /root/.ssh/id_rsa
      dest: /root/.ssh/id_rsa
      mode: 0600
      owner: root

  - name: get project
    git:
      repo: 'git@github.com:kakabomba/profireader.git'
      accept_hostkey: true
      dest: /var/profireader
      version: production

