---

- hosts: "postgres.p"
  remote_user: root
  become: no
  tasks:
    - name: install prerequisites
      become: yes
      apt: name={{ item }} state=latest update_cache=yes
      with_items:
        - libpq-dev
        - python-psycopg2
    - name: Usage
      debug:
        msg: ""
    - name: Install postgresql
      apt:
        update_cache: yes
        name: 'postgresql'
    - name: Copy postgres config file pg_hba.conf
      copy:
        src: ../postgres/pg_hba.conf
        dest: /etc/postgresql/9.4/main/pg_hba.conf
        mode: 0644
    - name: Copy postgres config file postgresql.conf
      copy:
        src: ../postgres/postgresql.conf
        dest: /etc/postgresql/9.4/main/postgresql.conf
        mode: 0644
    - name: Enable postgres
      service:
        name: postgresql
        state: restarted
        enabled: yes
    - name: create profi database
      sudo: yes
      sudo_user: postgres
      postgresql_db:
        name: profireader
    - name: create profi database
      sudo: yes
      sudo_user: postgres
      postgresql_user:
        db: profireader
        name: pfuser
        password: bAnach~tArski
